import streamlit as st
import matplotlib.pyplot as plt
import os
import json
import urllib.request
import urllib.error
import ssl

# ---------------------------------------
# Data makanan sederhana (100 gram)
# ---------------------------------------
foods = {
    "Nasi Putih": {"kalori": 175, "protein": 3.2, "karbo": 40, "lemak": 0.3},
    "Ayam Goreng": {"kalori": 250, "protein": 20, "karbo": 0, "lemak": 18},
    "Tempe": {"kalori": 150, "protein": 14, "karbo": 8, "lemak": 8},
    "Sayur Bayam": {"kalori": 40, "protein": 3, "karbo": 7, "lemak": 0.5},
    "Pisang": {"kalori": 90, "protein": 1, "karbo": 23, "lemak": 0.3},
    "Telur Rebus": {"kalori": 155, "protein": 13, "karbo": 1, "lemak": 11},
    "Tahu": {"kalori": 80, "protein": 8, "karbo": 2, "lemak": 4},
    "Nasi Goreng": {"kalori": 250, "protein": 6, "karbo": 32, "lemak": 9},
    "Mie Goreng": {"kalori": 270, "protein": 7, "karbo": 40, "lemak": 8},
    "Sate Ayam": {"kalori": 230, "protein": 18, "karbo": 6, "lemak": 14},
    "Rendang": {"kalori": 350, "protein": 15, "karbo": 4, "lemak": 28},
    "Bakso": {"kalori": 200, "protein": 12, "karbo": 10, "lemak": 12},
    "Soto Ayam": {"kalori": 90, "protein": 7, "karbo": 6, "lemak": 4},
    "Ayam Bakar": {"kalori": 190, "protein": 24, "karbo": 0, "lemak": 9},
    "Ikan Goreng": {"kalori": 220, "protein": 20, "karbo": 0, "lemak": 14},
    "Ikan Bakar": {"kalori": 180, "protein": 22, "karbo": 0, "lemak": 8},
    "Udang Goreng": {"kalori": 190, "protein": 24, "karbo": 0, "lemak": 9},
    "Tempe Goreng": {"kalori": 210, "protein": 19, "karbo": 8, "lemak": 12},
    "Tahu Goreng": {"kalori": 140, "protein": 12, "karbo": 3, "lemak": 8},
    "Roti Tawar": {"kalori": 265, "protein": 9, "karbo": 49, "lemak": 3.2},
    "Kentang Goreng": {"kalori": 312, "protein": 3.4, "karbo": 41, "lemak": 15},
    "Jagung Rebus": {"kalori": 96, "protein": 3.4, "karbo": 21, "lemak": 1.5},
    "Apel": {"kalori": 52, "protein": 0.3, "karbo": 14, "lemak": 0.2},
    "Keju Cheddar": {"kalori": 403, "protein": 25, "karbo": 1.3, "lemak": 33},
    "Susu UHT (sapi)": {"kalori": 60, "protein": 3.4, "karbo": 5, "lemak": 3.3},
    "Yogurt Plain": {"kalori": 59, "protein": 10, "karbo": 3.6, "lemak": 0.4},
    "Kacang Tanah (goreng)": {"kalori": 567, "protein": 25.8, "karbo": 16.1, "lemak": 49.2},
}

# ---------------------------------------
# Tampilan Utama
# ---------------------------------------
st.set_page_config(page_title="Kalkulator Kalori ", page_icon="🔥", layout="centered")

# ---------------------------------------
# Custom CSS for Gen Z Style
# ---------------------------------------
st.markdown("""
<style>
    /* -----------------------------
       Cool, high-contrast Gen Z theme
       subtle animations and accessible
       ----------------------------- */

    :root{
        --bg-1: #0f1724; /* deep navy */
        --bg-2: #0b1220; /* darker gradient end */
        --card: rgba(255,255,255,0.04);
        --muted: rgba(255,255,255,0.7);
        --accent-1: #7c5cff; /* violet */
        --accent-2: #00d4ff; /* aqua */
        --success: #34d399;
        --warn: #fb923c;
        --danger: #f43f5e;
        --glass-blur: 8px;
    }

    /* Respect user preference for reduced motion */
    @media (prefers-reduced-motion: reduce) {
        * { animation: none !important; transition: none !important; }
    }

    /* App background with slow-moving gradient */
    .stApp {
        background: linear-gradient(180deg, var(--bg-1) 0%, var(--bg-2) 100%);
        color: var(--muted);
        background-attachment: fixed;
        min-height: 100vh;
        transition: background 0.6s ease;
        font-family: Inter, ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial;
    }

    /* subtle animated shimmer for background */
    .stApp::before{
        content: "";
        position: fixed;
        inset: 0;
        background: linear-gradient(120deg, rgba(124,92,255,0.06), rgba(0,212,255,0.04), transparent 45%);
        pointer-events: none;
        mix-blend-mode: overlay;
        animation: bgShift 18s linear infinite;
        opacity: 1;
    }

    @keyframes bgShift{
        0% { transform: translate3d(-10%, -5%, 0) rotate(0.001deg); }
        50% { transform: translate3d(10%, 5%, 0) rotate(0.001deg); }
        100% { transform: translate3d(-10%, -5%, 0) rotate(0.001deg); }
    }

    /* Headers */
    h1, h2, h3 { color: #ffffff; letter-spacing: -0.5px; }

    /* Card style for containers */
    .stContainer, .st-cv { }

    /* Use Streamlit's autogenerated classes conservatively; target common widgets visually */
    .stButton>button, .stSelectbox>div, .stNumberInput>div, .stSlider>div {
        border-radius: 12px !important;
        background: linear-gradient(180deg, rgba(255,255,255,0.02), rgba(255,255,255,0.01));
        border: 1px solid rgba(255,255,255,0.06) !important;
        color: #ffffff !important;
        padding: .45rem .6rem !important;
        box-shadow: 0 4px 18px rgba(2,6,23,0.6);
        transition: transform .18s ease, box-shadow .18s ease, background .18s ease;
    }

    /* Slight lift on hover */
    .stButton>button:hover, .stSelectbox>div:hover, .stNumberInput>div:hover {
        transform: translateY(-3px);
        box-shadow: 0 8px 28px rgba(2,6,23,0.7);
    }

    /* Animated accent border on focused inputs */
    .stSelectbox>div:focus-within, .stNumberInput>div:focus-within, .stSlider>div:focus-within, .stTextInput>div:focus-within {
        outline: none !important;
        box-shadow: 0 6px 28px rgba(124,92,255,0.12), 0 0 0 3px rgba(124,92,255,0.06) !important;
        border-color: rgba(124,92,255,0.45) !important;
    }

    /* Metrics and result cards */
    .stMetric, .stMetric>div, .st-emotion-cache-1vzeuhh {
        background: linear-gradient(135deg, rgba(255,255,255,0.02), rgba(255,255,255,0.01));
        border-radius: 12px;
        padding: 0.9rem !important;
        color: #fff !important;
        border: 1px solid rgba(255,255,255,0.05);
        backdrop-filter: blur(var(--glass-blur));
        box-shadow: 0 6px 30px rgba(2,6,23,0.6);
        transition: transform .22s ease, box-shadow .22s ease;
    }

    .stMetric:hover { transform: translateY(-4px); }

    /* Progress bar styling */
    .stProgress > div > div > div {
        background: linear-gradient(90deg, var(--accent-1), var(--accent-2)) !important;
        border-radius: 999px !important;
    }

    /* Pie chart text color fix inside Streamlit's canvas */
    .stCanvas { color: #fff; }

    /* Button subtle pulse animation */
    @keyframes pulseAccent {
        0% { box-shadow: 0 0 0 0 rgba(124,92,255,0.18); }
        70% { box-shadow: 0 0 0 10px rgba(124,92,255,0.02); }
        100% { box-shadow: 0 0 0 0 rgba(124,92,255,0.0); }
    }

    .stButton>button:active {
        transform: translateY(0);
        animation: pulseAccent 1.6s ease-in-out;
    }

    /* Links and accents */
    a, .stMarkdown a { color: var(--accent-2); }

    /* Small responsive tweaks */
    @media (max-width: 640px) {
        .stButton>button, .stSelectbox>div, .stNumberInput>div { padding: .5rem .75rem !important; }
    }

</style>
""", unsafe_allow_html=True)


st.title("🔥 Kalkulator Kalori ")
st.caption("Hitung kalori & gizi harianmu, no ribet! ✨")

# ---------------------------------------
# Input Data Pengguna
# ---------------------------------------
with st.container():
    st.header("👤 Data Diri")
    col1, col2 = st.columns(2)
    with col1:
        gender = st.selectbox("Jenis Kelamin", ["Laki-laki", "Perempuan"])
        usia = st.slider("Usia (tahun)", 1, 100, 25)
        aktivitas = st.selectbox("Level Aktivitas", ["Santai (rebahan)", "Normal (kuliah/kerja)", "Sangat Aktif (nge-gym)"])
    with col2:
        berat = st.slider("Berat Badan (kg)", 1, 200, 60)
        tinggi = st.slider("Tinggi Badan (cm)", 100, 220, 165)

# ---------------------------------------
# Hitung BMR & TDEE
# ---------------------------------------
if gender == "Laki-laki":
    bmr = 10 * berat + 6.25 * tinggi - 5 * usia + 5
else:
    bmr = 10 * berat + 6.25 * tinggi - 5 * usia - 161

faktor = {"Santai (rebahan)": 1.2, "Normal (kuliah/kerja)": 1.55, "Sangat Aktif (nge-gym)": 1.725}
tdee = bmr * faktor[aktivitas]

st.success(f"**Kebutuhan Kalori Harianmu (TDEE):** {tdee:.0f} kkal")

# ---------------------------------------
# Input Makanan
# ---------------------------------------
with st.container():
    st.header("🍽️ Makanan Hari Ini")
    makanan = st.multiselect("Pilih makanan yang kamu makan:", list(foods.keys()))
    porsi = {}

    for m in makanan:
        porsi[m] = st.number_input(f"{m} (gram)", min_value=0.0, max_value=1000.0, step=10.0, key=f"porsi_{m}")

# ---------------------------------------
# Hitung Total Nutrisi
# ---------------------------------------
if makanan:
    total = {"kalori": 0, "protein": 0, "karbo": 0, "lemak": 0}
    for m, g in porsi.items():
        for n in total:
            total[n] += foods[m][n] * (g / 100)

    st.divider()
    
    with st.container():
        st.subheader("📊 Hasil Asupanmu")

        col1, col2 = st.columns(2)
        with col1:
            st.metric("Total Kalori", f"{total['kalori']:.1f} kkal")
            st.metric("Protein", f"{total['protein']:.1f} g")
        with col2:
            st.metric("Karbohidrat", f"{total['karbo']:.1f} g")
            st.metric("Lemak", f"{total['lemak']:.1f} g")

        # Progress bar kalori
        st.write("**Progress Kalori Harian:**")
        st.progress(min(total["kalori"] / tdee, 1.0))

        # Pie chart makronutrien
        st.write("**Komposisi Makro:**")
        fig, ax = plt.subplots(figsize=(3, 3))
        ax.patch.set_alpha(0) # Transparan background
        fig.patch.set_alpha(0)
        
        pie_colors = ['#ff9999','#66b3ff','#99ff99']
        ax.pie(
            [total["karbo"], total["protein"], total["lemak"]],
            labels=["Karbo", "Protein", "Lemak"],
            autopct="%1.1f%%",
            colors=pie_colors,
            textprops={"fontsize": 8, "color": "white"},
        )
        st.pyplot(fig)

    # ---------------------------------------
    # Rekomendasi Otomatis
    # ---------------------------------------
    st.divider()
    with st.container():
        st.subheader("💡 Rekomendasi Cepet")

        # Basic calorie status
        if total["kalori"] < 0.9 * tdee:
            st.info("Kalorimu masih kurang nih — tambah porsi karbo atau camilan sehat (pisang, roti, jagung). 🍌")
        elif total["kalori"] > 1.1 * tdee:
            st.warning("Kalori hari ini agak over. Kurangi gorengan atau porsi nasi/karbo, dan tambah sayur. 😉")
        else:
            st.success("Kalori sudah pas untuk hari ini — teruskan!")

        # Macro breakdown and suggestions
        prot = total.get("protein", 0)
        kar = total.get("karbo", 0)
        fat = total.get("lemak", 0)
        cal = total.get("kalori", 0)

        # calories from macros
        calories_from_prot = prot * 4
        calories_from_kar = kar * 4
        calories_from_fat = fat * 9
        total_macro_cals = max(calories_from_prot + calories_from_kar + calories_from_fat, 1)

        prot_pct = calories_from_prot / total_macro_cals
        kar_pct = calories_from_kar / total_macro_cals
        fat_pct = calories_from_fat / total_macro_cals

        st.write(f"Protein: {prot:.1f} g — Karbo: {kar:.1f} g — Lemak: {fat:.1f} g")
        st.write(f"Komposisi energi (perkiraan): Protein {prot_pct:.0%}, Karbo {kar_pct:.0%}, Lemak {fat_pct:.0%}")

        # Practical tips based on macros
        tips = []
        # Protein target suggestion: simple heuristic 1.2-1.6 g/kg for active, else 0.8-1.0
        protein_target = 1.0 * berat
        if aktivitas == "Sangat Aktif (nge-gym)":
            protein_target = 1.4 * berat

        if prot < 0.8 * protein_target:
            tips.append("Proteinmu masih kurang — tambahin telur, tahu, tempe, atau ayam sebagai lauk.")
        elif prot > 2.5 * berat:
            tips.append("Protein sudah sangat tinggi untuk 1 hari — variasikan sumber dan kurangi porsi besar.")

        # Carb guidance
        if kar < 0.4 * (cal / 4):
            tips.append("Karbo rendah — kalau butuh energi tambah nasi, roti, atau pisang sebelum aktivitas.")
        if fat > 0.35 * (cal / 9):
            tips.append("Lemak terlihat tinggi — kurangi makanan goreng/berminyak.")

        # Quick swaps
        swaps = []
        if any(x in str(makanan).lower() for x in ["goreng", "fried", "bakar"]) and cal > 1.1 * tdee:
            swaps.append("Ganti beberapa gorengan dengan tahu/tempe kukus atau sayur rebus untuk memangkas lemak.")

        if cal < 0.9 * tdee:
            swaps.append("Tambahkan snack sehat: yogurt + buah, segenggam kacang, atau telur rebus.")

        # Display tips
        if tips:
            for t in tips:
                st.info(t)
        else:
            st.write("Tidak ada isu makro besar yang terdeteksi — good job!")

        if swaps:
            st.write("Saran penggantian cepat:")
            for s in swaps:
                st.write(f"- {s}")

        # Extra recommendation: sample mini-meal plan to reach TDEE if under
        if cal < 0.9 * tdee:
            st.write("\nContoh penambahan 1 porsi untuk menambah ~300 kkal:")
            st.write("- 1 porsi nasi + 1 telur goreng (atau 2 sdm kacang) — sekitar 250-350 kkal")

        # Additional protein reminder
        if prot < 0.8 * (berat * 0.8):
            st.info("Biar otot makin jadi, tambahin protein dari telur atau tahu, kuy!")

        # End recommendations

        # -------------------------
        # Optional AI Assistant (ChatGPT)
        # -------------------------
        st.divider()
        st.subheader("🤖 AI Assistant (opsional)")
        st.write("Tanya asisten tentang meal planning, substitusi bahan, atau minta ide resep singkat.")

        ai_prompt = st.text_area("Tanya AI (contoh: " + "'Beri aku ide makan siang 400 kkal kaya protein'" + ")", height=80)
        ask_ai = st.button("Kirim ke AI")

        st.divider()
        st.subheader("🤖 AI Assistant (opsional)")
        st.write("Tanya asisten tentang meal planning, substitusi bahan, atau minta ide resep singkat.")

        ai_prompt = st.text_area(
            "Tanya AI (contoh: 'Beri aku ide makan siang 400 kkal kaya protein')",
            height=80
        )
        ask_ai = st.button("Kirim ke AI")

        # -------------------------
        # ✅ FIXED: ambil API key dengan benar
        # -------------------------
        def _get_openai_key():
            try:
                # Gunakan key dari secrets, bukan nama panjang di dalam kode
                return st.secrets["OPENAI_API_KEY"]
            except Exception:
                return os.environ.get("OPENAI_API_KEY")

        def call_openai_chat(prompt_text: str):
            api_key = _get_openai_key()
            if not api_key:
                return None, "🔑 OPENAI_API_KEY tidak ditemukan di st.secrets atau environment variables."

            url = "https://api.openai.com/v1/chat/completions"
            headers = {
                "Content-Type": "application/json",
                "Authorization": f"Bearer {api_key}",
            }

            # konteks intake
            context = (
                f"Current totals: kalori={cal:.1f} kcal, protein={prot:.1f} g, "
                f"karbo={kar:.1f} g, lemak={fat:.1f} g, TDEE={tdee:.0f} kcal."
            )
            full_prompt = context + "\n\nUser question: " + prompt_text

            body = {
                "model": "gpt-3.5-turbo",
                "messages": [
                    {
                        "role": "system",
                        "content": "You are a helpful nutrition assistant that gives concise, actionable advice and simple recipe/meal suggestions."
                    },
                    {"role": "user", "content": full_prompt},
                ],
                "max_tokens": 300,
                "temperature": 0.7,
            }

            data = json.dumps(body).encode("utf-8")
            req = urllib.request.Request(url, data=data, headers=headers, method="POST")

            try:
                ctx = ssl.create_default_context()
                with urllib.request.urlopen(req, context=ctx, timeout=15) as resp:
                    j = json.loads(resp.read().decode("utf-8"))
                    return j["choices"][0]["message"]["content"], None
            except urllib.error.HTTPError as e:
                try:
                    err = e.read().decode()
                except Exception:
                    err = str(e)
                return None, f"HTTPError: {e.code} {err}"
            except Exception as e:
                return None, str(e)

        if ask_ai and ai_prompt.strip():
            with st.spinner("Menghubungi AI..."):
                resp, err = call_openai_chat(ai_prompt.strip())
            if err:
                st.error(f"Gagal: {err}")
            elif resp:
                st.markdown("**AI Response:**")
                st.info(resp)
            else:
                st.write("Tidak ada jawaban dari AI.")
else:
    st.write("💬 Pilih makanan & masukin porsinya buat liat hasilnya, bestie.")
